import { Component } from '@angular/core';
import { Book } from '../model/Book';
import { NgFor } from '@angular/common';

@Component({
  selector: 'app-directive-demo-for',
  imports: [NgFor],
  templateUrl: './directive-demo-for.component.html',
  styleUrl: './directive-demo-for.component.css'
})
export class DirectiveDemoForComponent {
  books: Book[] = [
    { title: 'Book 1', description: 'Reclaim your focus in 48 hours or less. Do you keep procrastinating? Do you feel restless and unable to focus on your work? Do you have trouble getting excited about major goals? If so, you might need a dopamine detox. In today’s world where distractions are everywhere, the ability to focus has become more and more difficult to achieve. We are constantly being stimulated, feeling restless, often without knowing why. When the time comes to work, we suddenly find an excess of other things to do. Instead of working toward our goals, we go for a walk, grab a coffee, or check our emails. Everything seems like a great idea—everything except the very things we should be doing. Do you recognize yourself in the above situation? If so, don’t worry. You’re simply overstimulated. Dopamine Detox will help you lower your level of stimulation and regain focus in 48 hours or less,so that you can tackle your key tasks. More specifically, in Dopamine Detox you’ll discover: what dopamine is and how it works; the main benefits of completing a dopamine detox; 3 simple steps to implement a successful detox in the next 48 hours; practical exercises to eliminate distractions and boost your focus; simple tools and techniques to avoid overstimulation and help you stay focused, and much more. Dopamine Detox is your must-read, must-follow guide to help you remove distractions so you can finally work on your goals with ease. If you like easy-to-understand strategies, practical exercises, and no-nonsense teaching, you will love this book.', path: "assets/book/book1.jpg" },
    { title: 'Book 2', description: 'Reclaim your focus in 48 hours or less. Do you keep procrastinating? Do you feel restless and unable to focus on your work? Do you have trouble getting excited about major goals? If so, you might need a dopamine detox. In today’s world where distractions are everywhere, the ability to focus has become more and more difficult to achieve. We are constantly being stimulated, feeling restless, often without knowing why. When the time comes to work, we suddenly find an excess of other things to do. Instead of working toward our goals, we go for a walk, grab a coffee, or check our emails. Everything seems like a great idea—everything except the very things we should be doing. Do you recognize yourself in the above situation? If so, don’t worry. You’re simply overstimulated. Dopamine Detox will help you lower your level of stimulation and regain focus in 48 hours or less,so that you can tackle your key tasks.', path: "assets/book/book2.jpg" },
    { title: 'Book 3', description: 'This is the description of Book 3.', path: "assets/book/book3.jpg" },
    { title: 'Book 4', description: 'TMore specifically, in Dopamine Detox you’ll discover: what dopamine is and how it works; the main benefits of completing a dopamine detox; 3 simple steps to implement a successful detox in the next 48 hours; practical exercises to eliminate distractions and boost your focus; simple tools and techniques to avoid overstimulation and help you stay focused, and much more. Dopamine Detox is your must-read, must-follow guide to help you remove distractions so you can finally work on your goals with ease. If you like easy-to-understand strategies, practical exercises, and no-nonsense teaching, you will love this book.', path: "assets/book/book1.jpg" }
  ];
}
